server {
    listen 80;
    
    # Configuración de gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # Caché de archivos estáticos
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
    
    # Evitar el caché para el index.html
    location = /index.html {
        root /usr/share/nginx/html;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}